### PR TITLE
Tags for articles

### PR DESCRIPTION
**Pull request by harman28**
Enhancement described in #3

### CODE REVIEW

**Comment by icyflame** [comment]
@harman28 It seems merging the other PR in lead to conflicts on this branch. Please rebase onto the latest master branch, and I think we should be good to go on this patch.

**Comment by harman28** [comment]
@icyflame Updated.

**Comment by icyflame** [comment]
Thanks @harman28. I will review as soon as I can, and merge if there are no issues! Thanks for your work on this :smile:

**Comment by icyflame** [comment]
@harman28 Hi, I pulled in your changes, but when I pushed it to PG (on Heroku) it stopped working because of some differences between Sqlite and PG (I think).

I changed the format of the `tags` field to ensure that it is a simple, comma-separated string, and there are no problems with any database that is used.

ActiveRecord stores it as YAML and PG doesn't play well with that? Not sure what went wrong, but I have solved it now.

Thanks for your contributions! :smile:

**Pull request merged**
